basePath: /api/v1/auth
definitions:
  nrs-authentication_internal_dto.AttachRoleResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  nrs-authentication_internal_dto.AttributeTypeSwagger:
    properties:
      Name:
        type: string
      Value:
        type: string
    type: object
  nrs-authentication_internal_dto.ListUsersOutputSwagger:
    properties:
      PaginationToken:
        type: string
      ResultMetadata:
        $ref: '#/definitions/nrs-authentication_internal_dto.MetadataSwagger'
      Users:
        items:
          $ref: '#/definitions/nrs-authentication_internal_dto.UserTypeSwagger'
        type: array
    type: object
  nrs-authentication_internal_dto.MFAOptionTypeSwagger:
    properties:
      AttributeName:
        type: string
      DeliveryMedium:
        type: string
    type: object
  nrs-authentication_internal_dto.MetadataSwagger:
    type: object
  nrs-authentication_internal_dto.UserTypeSwagger:
    properties:
      Attributes:
        items:
          $ref: '#/definitions/nrs-authentication_internal_dto.AttributeTypeSwagger'
        type: array
      Enabled:
        type: boolean
      MFAOptions:
        items:
          $ref: '#/definitions/nrs-authentication_internal_dto.MFAOptionTypeSwagger'
        type: array
      UserCreateDate:
        type: string
      UserLastModifiedDate:
        type: string
      UserStatus:
        type: string
      Username:
        type: string
    type: object
  types.AttributeType:
    properties:
      name:
        description: The name of the attribute, for example email or custom:department .
        type: string
      value:
        description: The value of the attribute.
        type: string
    type: object
  types.DeliveryMediumType:
    enum:
    - SMS
    - EMAIL
    type: string
    x-enum-varnames:
    - DeliveryMediumTypeSms
    - DeliveryMediumTypeEmail
  types.MFAOptionType:
    properties:
      attributeName:
        description: The attribute name of the MFA option type. The only valid value is phone_number .
        type: string
      deliveryMedium:
        allOf:
        - $ref: '#/definitions/types.DeliveryMediumType'
        description: The delivery medium to send the MFA code.
    type: object
  types.UserStatusType:
    enum:
    - UNCONFIRMED
    - CONFIRMED
    - ARCHIVED
    - COMPROMISED
    - UNKNOWN
    - RESET_REQUIRED
    - FORCE_CHANGE_PASSWORD
    - EXTERNAL_PROVIDER
    type: string
    x-enum-varnames:
    - UserStatusTypeUnconfirmed
    - UserStatusTypeConfirmed
    - UserStatusTypeArchived
    - UserStatusTypeCompromised
    - UserStatusTypeUnknown
    - UserStatusTypeResetRequired
    - UserStatusTypeForceChangePassword
    - UserStatusTypeExternalProvider
  types.UserType:
    properties:
      attributes:
        description: Names and values of a user's attributes, for example email .
        items:
          $ref: '#/definitions/types.AttributeType'
        type: array
      enabled:
        description: Indicates whether the user's account is enabled or disabled.
        type: boolean
      mfaoptions:
        description: The user's MFA configuration.
        items:
          $ref: '#/definitions/types.MFAOptionType'
        type: array
      userCreateDate:
        description: The date and time when the item was created.
        type: string
      userLastModifiedDate:
        description: The date and time when the item was modified.
        type: string
      userStatus:
        allOf:
        - $ref: '#/definitions/types.UserStatusType'
      username:
        description: The user's username.
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Handles authentication utilities
  title: nrs-authentication
  version: "1.0"
paths:
  /attach-role:
    post:
      consumes:
      - application/json
      description: attaches a role to a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/nrs-authentication_internal_dto.AttachRoleResponse'
      summary: Attach a role to a user
      tags:
      - roles
  /get-user:
    get:
      consumes:
      - application/json
      description: Returns a user by email.
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User lookup result.
          schema:
            $ref: '#/definitions/nrs-authentication_internal_dto.ListUsersOutputSwagger'
      summary: Get user by email
      tags:
      - users
  /me/get-facility-users:
    get:
      consumes:
      - application/json
      description: returns a list of facility users
      parameters:
      - description: facility_code
        in: query
        name: facility_code
        required: true
        type: string
      - description: group
        in: query
        name: group
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.UserType'
            type: array
      summary: Get users for a facility
      tags:
      - users
swagger: "2.0"
